### ISSUE TITLE
Priviliges

### ISSUE THREAD

**Issue by BeastyBlacksmith** [sisl/tufte_algorithms_book#4]
is there any way to run the python scripts ( or get the things done they do ) without having to use `sudo`?
I don't have admin rights on my work machine.

**Comment by tawheeler** [comment]
Hi @BeastyBlacksmith - I do not know.

**Comment by johnnychen94** [comment]
`sudo` is required because by default the python used is `/usr/bin/python` that installs the scripts into `/usr/bin` (or `/usr/local/bin`, I'm not sure), which you don't have write-permission.

A simple strategy is to install a python into someplace you have write-permission. For example, anaconda3 installs python into `/home/USER/anaconda3/bin`. In this case, you don't need to add `sudo` prefix.

P.S. in case you are not aware, `which python` tells you the python you're using.

**Comment by BeastyBlacksmith** [comment]
It is also possible to use e.g. `python setup.py install --user` which will install to `homedir/.local/bin` (at least on Linux).
